---
# https://docs.rackslab.io/slurm-web/install/quickstart/packages.html

# sudo useradd -M -r -s /usr/sbin/nologin -U slurmrestd

- name: Ensure users exists
  block:
    - name: Ensure users exists | slurmrestd group
      ansible.builtin.group:
        name: slurmrestd
        state: present

    - name: Ensure users exists | slurm-web group
      ansible.builtin.group:
        name: slurm-web
        state: present

    - name: Ensure users exists | Create a slurmrestd system user
      ansible.builtin.user:
        name: slurmrestd
        group: slurmrestd
        create_home: no
        system: yes
        shell: /usr/sbin/nologin
        # groups: slurm,slurm-web
        groups: slurmrestd
        append: no

    - name: Ensure users exists | Create a slurm-web system user
      ansible.builtin.user:
        name: slurm-web
        group: slurm-web
        create_home: no
        system: yes
        shell: /usr/sbin/nologin
        groups: slurm,slurmrestd
        append: no

  when: (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
  ignore_errors: "{{ ansible_check_mode }}"
  become: yes
  tags: [slurm, slurm_web, slurm_web_install]



- name: Ensure Slurm configuration exists
  block:
    - name: Ensure Slurm configuration exists | SlurmRESTd configuration directories
      file:
        path: "{{ item }}"
        state: directory
        owner: slurmrestd
        group: slurmrestd
        mode: '0755'
      loop:
        - /etc/systemd/system/slurmrestd.service.d/

    - name: Ensure Slurm configuration exists | SlurmRESTd socket directories
      file:
        path: "{{ item }}"
        state: directory
        owner: slurmrestd
        group: slurmrestd
        mode: '0775'
      loop:
        - /run/slurmrestd/

    - name: Ensure Slurm configuration exists | SlurmWEB configuration directories
      file:
        path: "{{ item }}"
        state: directory
        owner: slurm-web
        group: slurm-web
        mode: '0755'
      loop:
        - /etc/systemd/system/slurm-web-agent.service.d/
        - /etc/systemd/system/slurm-web-gateway.service.d/
        - /etc/slurm-web

    - name: Ensure Slurm configuration exists | Template SlurmRESTd configuration files
      template:
        src: "slurmrestd.conf.j2"
        dest: "/etc/systemd/system/slurmrestd.service.d/slurmrestd.conf"
        owner: slurmrestd
        group: slurmrestd
        mode: '0644'

    - name: Ensure Slurm configuration exists | Template SlurmWEB Agent configuration files
      template:
        src: "slurm-web-agent.conf.j2"
        dest: "/etc/systemd/system/slurm-web-agent.service.d/slurm-web-agent.conf"
        owner: slurm-web
        group: slurm-web
        mode: '0644'

    - name: Ensure Slurm configuration exists | Template SlurmWEB Gateway configuration files
      template:
        src: "slurm-web-gateway.conf.j2"
        dest: "/etc/systemd/system/slurm-web-gateway.service.d/slurm-web-gateway.conf"
        owner: slurm-web
        group: slurm-web
        mode: '0644'

    - name: Ensure Slurm configuration exists | Template SlurmWEB configuration files
      template:
        src: "{{ item }}.j2"
        dest: "/etc/slurm-web/{{ item }}"
        owner: slurm-web
        group: slurm-web
        mode: '0600'
      loop:
        - agent.ini
        - gateway.ini
      # notify: restart slurm services
      # when: (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
      # ignore_errors: "{{ ansible_check_mode }}"
      # become: yes
      # tags: [slurm, slurm_web, slurm_web_install]

  when: (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
  ignore_errors: "{{ ansible_check_mode }}"
  become: yes
  tags: [slurm, slurm_web, slurm_web_install]



# https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/apt_repository_module.html
- name: Add slurmWEB repository
  block:
    # - name: slurmWEB | no apt key
    #   ansible.builtin.get_url:
    #     url: https://pkgs.rackslab.io/keyring.asc
    #     dest: /usr/share/keyrings/rackslab.gpg

    # - name: Check if rackslab key exists
    #   stat:
    #     path: "/usr/share/keyrings/rackslab.gpg"
    #   register: rackslab_key_path

    # - name: slurmWEB | add apt key
    #   ansible.builtin.command: "curl -sS https://pkgs.rackslab.io/keyring.asc | gpg --dearmor | tee /usr/share/keyrings/rackslab.gpg > /dev/null"
    #   when: not rackslab_key_path.stat.exists

    # - name: slurmWEB | apt source main
    #   deb822_repository:
    #     repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/rackslab.gpg] https://pkgs.rackslab.io/deb ubuntu24.04 main"
    #     state: present

    # - name: slurmWEB | apt source slurmweb
    #   deb822_repository:
    #     repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/rackslab.gpg] https://pkgs.rackslab.io/deb ubuntu24.04 slurmweb-7"
    #     state: present

    - name: slurmWEB | Add repo using key from URL
      deb822_repository:
        name: rackslab
        types: deb
        uris: https://pkgs.rackslab.io/deb
        # suites: 'ubuntu24.04'
        # components: main slurmweb-6
        suites: 'ubuntu26.04'
        components: main slurmweb-7
        architectures: amd64
        signed_by: https://pkgs.rackslab.io/keyring.asc

    - name: slurmWEB | apt Install packages
      package:
        name: "{{ item }}"
        state: present
        update_cache: true  
      loop: "{{ (ansible_facts['os_family'] == 'Debian') | ternary(slurm_packages_controller_apt + slurm_packages_shared_apt, slurm_packages_controller_rpm + slurm_packages_shared_rpm) }}"
      # when: (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
      # tags: [slurm, slurm_web, slurm_web_install]
      # become: yes
      # ignore_errors: "{{ ansible_check_mode }}"
  when: (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
  tags: [slurm, slurmrest, slurm_web, slurm_rest_install, slurm_web_install]
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"



- name: Create SlurmWEB Session Key
  block:
    - name: SlurmWEB Session Key | Look for Key
      stat:
        path: "/var/lib/slurm-web/session.key"
      register: slurm_web_session_key
      # when: (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
      # tags: [slurm, slurm_web, slurm_web_install]
      # become: yes
      # ignore_errors: "{{ ansible_check_mode }}"

    - name: SlurmWEB Session Key | Create new Key
      command: "slurm-web gen-session-key --set-ownership"
      when: (not slurm_web_session_key.stat.exists)
      # when: (not slurm_web_session_key.stat.exists) and (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
      # tags: [slurm, slurm_web, slurm_web_install]
      # become: yes
      # ignore_errors: "{{ ansible_check_mode }}"

    - name: SlurmWEB Session Key | Change file ownership, group and permissions
      file:
        path: /var/lib/slurm-web/session.key
        owner: slurm-web
        group: slurm-web
        mode: '0600'
  when: (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
  tags: [slurm, slurm_web, slurm_web_install]
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"



- name: Create SlurmWEB JWT Key
  block:
    - name: Create SlurmWEB JWT Key | Look for Key
      stat:
        path: "/var/lib/slurm-web/jwt.key"
      register: slurm_web_jwt_key

    - name: Create new SlurmWEB JWT Key | Generate if not exists
      command: "slurm-web gen-jwt-key --set-ownership"
      when: (not slurm_web_jwt_key.stat.exists)

    - name: SlurmWEB JWT Key | Change file ownership, group and permissions
      file:
        path: /var/lib/slurm-web/jwt.key
        owner: slurm-web
        group: slurm-web
        mode: '0600'
  when: (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
  tags: [slurm, slurm_web, slurm_web_install]
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"



- name: Copy Slurm JWT signing key
  ansible.builtin.copy:
    remote_src: true
    src: /var/spool/slurmd/jwt_hs256.key
    dest: /var/lib/slurm-web/slurmrestd.key
    owner: slurm-web
    group: slurm-web
    mode: '0400'
  when: (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
  tags: [slurm, slurm_web, slurm_web_install]
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"



- name: Check SlurmWEB
  command: "slurm-web connect-check"
  when: (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
  tags: [slurm, slurm_web, slurm_web_install]
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"



- name: Enable and start Slurm Controller services in Controllers
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: restarted
    daemon_reexec: yes
    daemon_reload: yes
  loop:
    - slurmrestd
    - slurm-web-agent
    - slurm-web-gateway
  when: (inventory_hostname in groups['slurm_controllers']) and slurm_web_activated
  tags: [slurm, slurm_web, slurm_rest, slurm_web_install, slurm_rest_install]
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
