---
- name: Deploy Slurm
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: build_dependencies
    - role: slurm_base
    - role: slurm_user
    - role: munge
    - role: mariadb
    - role: slurm_config
    - role: slurm_install
    - role: slurm_web
    - role: storage
