---
base_packages_rpm:
  - gcc
  - gcc-c++
  - make
  - openssl-devel
  - pam-devel
  - perl-ExtUtils-MakeMaker
  - python3-devel
  - readline-devel
  - rpm-build
  - tar
  - lua
  - lua-devel
  - readline
  - readline-devel
  - cmake
  - git
  - jansson
  - jansson-devel
  - autoconf
  - pkgconf
  - libtool
  - wget
  - bzip2
  - dbus-devel
  - systemd-devel
  - mariadb105-devel

# https://github.com/vishalpapan/ansible-slurm-deployment/blob/main/roles/build_dependencies/vars/main.yml
base_packages_apt:
  - gcc
  - g++
  - make
  - libssl-dev
  - libpam0g-dev
  - libextutils-makemaker-cpanfile-perl
  - python3-dev
  - tar
  - lua5.4
  - liblua5.4-dev
  - libreadline8t64
  - libreadline6-dev
  - cmake
  - git
  - libjansson4
  - libjansson-dev
  - autoconf
  - pkgconf
  - libtool
  - wget
  - bzip2
  - libdbus-1-dev
  - libsystemd-dev
  - libmariadb-dev

dev_libraries_rpm:
  - lua-devel
  - pam-devel
  - perl-ExtUtils-MakeMaker
  - readline-devel
  - openssl-devel
  - python3-devel
  - dbus-devel
  - systemd-devel

dev_libraries_apt:
  - liblua5.4-dev
  - libpam0g-dev
  - libextutils-makemaker-cpanfile-perl
  - libreadline6-dev
  - libssl-dev
  - python3-dev
  - libdbus-1-dev
  - libsystemd-dev
