---
base_packages_rpm:
  - autoconf
  - bzip2
  - cmake
  - dbus-devel
  - gcc
  - gcc-c++
  - git
  - jansson
  - jansson-devel
  - libtool
  - lua
  - lua-devel
  - make
  - mariadb105-devel
  - numactl-devel
  - openssl-devel
  - pam-devel
  - perl-ExtUtils-MakeMaker
  - pkgconf
  - python3-devel
  - readline
  - readline-devel
  - rpm-build
  - systemd-devel
  - tar
  - wget

# https://github.com/vishalpapan/ansible-slurm-deployment/blob/main/roles/build_dependencies/vars/main.yml
base_packages_apt:
  - autoconf
  - bzip2
  - cmake
  - g++
  - gcc
  - git
  - libssl-dev
  - libpam0g-dev
  - libextutils-makemaker-cpanfile-perl
  - libjansson4
  - libjansson-dev
  - liblua5.4-dev
  - libpmix2
  - libreadline8t64
  - libreadline6-dev
  - libtool
  - lua5.4
  - make
  - openmpi-bin
  - python3-dev
  - pkgconf
  - tar
  - wget

dev_libraries_rpm:
  - dbus-devel
  - lua-devel
  - openssl-devel
  - pam-devel
  - perl-ExtUtils-MakeMaker
  - python3-devel
  - readline-devel
  - systemd-devel

dev_libraries_apt:
  - libdbus-1-dev
  - libextutils-makemaker-cpanfile-perl
  - liblua5.4-dev
  - libmariadb-dev
  - libnuma-dev
  - libopenmpi-dev
  - libpam0g-dev
  - libpmix-dev
  - libreadline6-dev
  - libssl-dev
  - libsystemd-dev
  - python3-dev
