---
# https://github.com/vishalpapan/ansible-slurm-deployment/blob/main/roles/json_c/defaults/main.yml
# https://github.com/json-c/json-c/tags

json_c_repo: "https://github.com/json-c/json-c.git"
json_c_version: "json-c-0.19-20260627"
# json_c_version: "json-c-0.15-20200726"
json_c_source_dir: "/home/{{ ansible_user }}/slurm-files/json-c"
json_c_build_dir: "/home/{{ ansible_user }}/slurm-files/json-c-build"