---
slurm_packages_shared_rpm: []
slurm_packages_controller_rpm: []
slurm_packages_worker_rpm: []



slurm_packages_shared_apt:
- slurm-client
- slurmdbd

slurm_packages_controller_apt:
- slurmctld
- slurm-wlm-mysql-plugin

slurm_packages_worker_apt:
- slurmd

