---
- name: Create slurm-files directory
  file:
    path: "/home/{{ ansible_user }}/slurm-files"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
