---
# Pre-defined password (optional - will generate random if not set)
slurm_db_password: ""

# MariaDB packages
mariadb_packages_rpm:
  - mariadb105-server
  - mariadb105-devel
  - mariadb105

# MariaDB packages
mariadb_packages_apt:
  - mariadb-server
  - libmariadb-dev
  - mariadb-client