---
- name: Install base dependencies and build tools
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ (ansible_facts['os_family'] == 'Debian') | ternary(base_packages_apt, base_packages_rpm) }}"
  tags: base_deps

- name: Install Development libraries
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ (ansible_facts['os_family'] == 'Debian') | ternary(dev_libraries_apt, dev_libraries_rpm) }}"
  tags: dev_libs

