---
- name: Create Slurm configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'
  loop:
    - /etc/slurm
    - /var/spool/slurmctld
    - /var/spool/slurmd
    - /var/log/slurm
    - /run/slurm
    - /run/slurmdbd
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  tags: [slurm, slurm_config]

- name: Template Slurm configuration files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/slurm/{{ item }}"
    owner: slurm
    group: slurm
    mode: '0600'
  loop:
    - slurm.conf
    - slurmdbd.conf
    - topology.conf
    - cgroup.conf
  # notify: restart slurm services
  ignore_errors: "{{ ansible_check_mode }}"
  become: yes
  tags: [slurm, slurm_config, slurm_config_files]

- name: Set proper ownership on Slurm directories
  file:
    path: "{{ item }}"
    owner: slurm
    group: slurm
    recurse: yes
  loop:
    - /var/spool/slurmctld
    - /var/spool/slurmd
    - /var/log/slurm
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  tags: [slurm, slurm_config]



- name: Enable and start Slurm CTL services in Controllers
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - slurmctld
    # - slurmdbd
  become: yes
  when: (disable_slurmd_on_controller | default(true)) and (inventory_hostname in groups['slurm_controllers'])
  ignore_errors: "{{ ansible_check_mode }}"
  tags: [slurm, slurm_config]

# - name: Disable and stop Slurm Daemon services in Controllers
#   systemd:
#     name: "{{ item }}"
#     enabled: no
#     state: stopped
#   loop:
#     - slurmd
#   become: yes
#   when: inventory_hostname in groups['slurm_controllers']
#   ignore_errors: "{{ ansible_check_mode }}"
#   tags: [slurm, slurm_config]



# - name: Disable and Stop Slurm CTL services in Workers
#   systemd:
#     name: "{{ item }}"
#     enabled: no
#     state: stopped
#   loop:
#     - slurmctld
#   become: yes
#   when: (disable_slurmd_on_controller | default(true)) and (inventory_hostname in groups['slurm_computes'])
#   ignore_errors: "{{ ansible_check_mode }}"
#   tags: [slurm, slurm_config]

- name: Enable and start Slurm Daemon services in Workers
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    # - slurmdbd
    - slurmd
  become: yes
  when: inventory_hostname in groups['slurm_computes']
  ignore_errors: "{{ ansible_check_mode }}"
  tags: [slurm, slurm_config]



- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes
  # when: inventory_hostname in groups['slurm_controllers']
  ignore_errors: "{{ ansible_check_mode }}"
  tags: [slurm, slurm_config]
